name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose2 pylint flask flask-json-schema docopt requests
    - name: Analysing the user_server with pylint
      run: |
        pylint user_server.py
    - name: Analysing the db_handling with pylint
      run: |
        pylint pypastebin/db_handling.py
    - name: Run integration tests
      run: |
        nose2
    - name: Run unittests tests
      run: |
        nose2 tests.tests_db_handling
